default_stages: [commit, manual]
fail_fast: false

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        language: node
        entry: commitlint --edit --config ./test/config/commit.json
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml

  - repo: local
    hooks:
      - id: format
        args: [
          '-c',
          '.eslintrc.js',
          '--fix',
          '--ignore-pattern=!.eslintrc.js',
          './dev',
          './ops',
          './src',
          './test'
        ]
        entry: eslint
        files: \.js(on)?$
        language: node
        name: Formatting files
        pass_filenames: false

  - repo: local
    hooks:
      - id: eslint
        args: [
          '-c',
          '.eslintrc.js',
          '--ignore-pattern=!.eslintrc.js',
          './dev',
          './ops',
          './src',
          './test'
        ]
        entry: eslint
        files: \.js(on)?$
        language: node
        name: Linting JS files
        pass_filenames: false

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shellcheck
        name: Linting SH files

  - repo: local
    hooks:
      - id: test
        entry: /bin/sh -c
        args: [
          "rm -f elemint.dev.js; NODE_ENV=test node ops/util/include.js; karma start test/config/karma.js"
        ]
        language: node
        name: Running tests
        pass_filenames: false
