default_stages: [commit, manual]

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        language: node
        entry: commitlint --edit --config ./test/config/commit.json
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.13.0-1
    hooks:
      - id: eslint
          additional_dependencies:
            - eslint@^7.13.0-1
            - eslint-config-airbnb@^18.2.1
            - eslint-config-standard@^14.1.1
            - eslint-plugin-disable@^2.0.1
            - eslint-plugin-import@^2.22.1
            - eslint-plugin-json@^2.1.2
            - eslint-plugin-jsx-a11y@^6.4.1
            - eslint-plugin-node@^11.1.0
            - eslint-plugin-promise@^4.2.1
            - eslint-plugin-react@^7.21.5
            - eslint-plugin-standard@^4.1.0

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shellcheck

  - repo: https://github.com/prettier/prettier
    rev: "2.1.2"
    hooks:
      - id: prettier
